### ISSUE TITLE
Các nhóm làm tài liệu tiếng Anh và tiếng Việt của môn học

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/int3117-2018#1]
Hoàn thiện tài liệu sau:
https://docs.google.com/document/d/18-QpPhm2HUK8GArR2zYokB5q39BSgng7XyGHFxWjE4E/edit#

Cụ thể:
- Lấy nội dung tiếng Anh đưa vào tài liệu và chỉnh sửa nội dung (xuống dòng các đoạn cho đúng)
- Tóm tắt nội dung tiếng Anh lại bằng nội dung tiếng Việt

Hạn hoàn thành: 1/9/2018

**Comment by ducnhienbg270** [comment]
#hoi_dap
Thưa thầy, các nhóm còn lại viết ra các bài tập là viết ra các Quiz của mỗi tuần phải không ạ?

**Comment by truonganhhoang** [comment]
Ừ.. các nhóm còn lại trước mắt đọc rà soát và kiểm thử lại các tài liệu của các nhóm khác đã làm, nhắc nhở khi chưa làm nhé.
