### ISSUE TITLE
Nguyen Anh Quang

### ISSUE THREAD

**Issue by Lego1st** [truonganhhoang/int3117-2018#105]
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/NguyenAnhQuang/Stack/src/main/java/oop/util/Stack.java#L17

Dòng trống ở đây là không cần thiết, dòng trống chỉ nên dùng để chia thành các khối lệnh có chức năng khác nhau (ví dụ như khối khai báo và khối thực thi)

**Comment by Neokun** [comment]
@Lego1st  đã fix, close đi ô
