### ISSUE TITLE
Nguyen Tuan Anh

### ISSUE THREAD

**Issue by Neokun** [truonganhhoang/int3117-2018#108]
dòng trống ở đây là thừa thãi, nên hạn chế các dòng chống không cần thiết để hạn chế code quá dài
Dòng trống chủ yếu dùng để tách các khối lệnh chức năng khác nhau

https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/NguyenTuanAnh/src/com/company/Stack.java#L53

**Comment by piggy2303** [comment]
ok mình đã sửa, Cảm ơn bạn
