### ISSUE TITLE
NguyenVanPhuc

### ISSUE THREAD

**Issue by minhpc225** [truonganhhoang/int3117-2018#110]
* Chưa có mô tả lớp
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/NguyenVanPhuc/src/test/ScholarshipTest.java#L7
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/NguyenVanPhuc/src/main/Scholarship.java#L4

* Chưa có mô tả testcase
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/NguyenVanPhuc/src/test/ScholarshipTest.java#L27

* Chưa có mô tả phương thức
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/NguyenVanPhuc/src/main/Scholarship.java#L8

**Comment by phucnguyenbn9x** [comment]
xem xong đóng issue.
