### ISSUE TITLE
PhamNgocDuy

### ISSUE THREAD

**Issue by TranPhuongAnh** [truonganhhoang/int3117-2018#113]
* Hàm này cần phân biệt giữa 2 trường hợp vô nghiệm và vô số nghiệm, không nên trả về đều là 0
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/PhamNgocDuy/GiaiPtBac2/src/giaiptbac2/PhuongTrinhBac2.java#L62-L73
Nên sửa thành:
Trả về 0 khi vô nghiệm
Trả về -1 khi vô số nghiệm

* Hình như mô tả nhầm?
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/PhamNgocDuy/GiaiPtBac2/test/test/TestGPTB2.java#L39-L48
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/PhamNgocDuy/GiaiPtBac2/test/test/TestGPTB2.java#L50-L57

* Nên test trường hợp PTB2 có vô số nghiệm

**Comment by phamngocduy98** [comment]
> * Hàm này cần phân biệt giữa 2 trường hợp vô nghiệm và vô số nghiệm, không nên trả về đều là 0
>
> https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/PhamNgocDuy/GiaiPtBac2/src/giaiptbac2/PhuongTrinhBac2.java#L62-L73
>
>   Nên sửa thành:
>   Trả về 0 khi vô nghiệm
>   Trả về -1 khi vô số nghiệm

Theo ý mình, hàm getSoNghiem() trả về độ dài của mảng nghiệm trong getNghiem()
nếu return -1 thì không ổn!
