### ISSUE TITLE
TranMinhTien

### ISSUE THREAD

**Issue by chocolinhbar** [truonganhhoang/int3117-2018#117]
- Dòng trống nên được đặt ở giữa biến cục bộ cuối và câu lệnh đầu tiên trong một hàm (oracle.com, Java Code Conventions, 8.1 Blank lines)
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/TranMinhTien/Model.java#L7

- Nên dùng ngoặc đơn trong các biểu thức có các toán tử hỗn hợp để làm rõ thứ tự ưu tiên (oracle.com, Java Code Conventions, 10.5.1 Parentheses)
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/TranMinhTien/Model.java#L8

- Các câu lệnh if nên luôn có ngoặc nhọn (oracle.com, Java Code Conventions, 7.4 if, if-else, if-else-if-else Statements)
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/TranMinhTien/Model.java#L9

- Việc sử dụng dòng trống (oracle.com, Java Code Conventions, 8.1 Blank lines); hai dòng trống sau không cần thiết:
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/TranMinhTien/testModel.java#L24
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/TranMinhTien/testModel.java#L32

**Comment by tienminhuet** [comment]
close hộ mình với
