### ISSUE TITLE
NguyenDucThang

### ISSUE THREAD

**Issue by vuvanquy1998** [truonganhhoang/int3117-2018#119]
- Thầy bảo di chuyển file  AppTest.java và LeapYear.java ra ngoài, còn lại xoá hết pro ơi  . 

- Nên đặt dòng trống ở giữa biến cục bộ cuối và câu lệnh đầu tiên trong một hàm .
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/NguyenDucThang/src/main/java/LeapYear.java#L9
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/NguyenDucThang/src/main/java/LeapYear.java#L18
- Cấu trúc trong các lệnh if   else nên để trong {}
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/NguyenDucThang/src/main/java/LeapYear.java#L12

- Tên các hàm là động từ
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/NguyenDucThang/src/test/java/AppTest.java#L16
- Các biểu thức toán tử hỗn hợp thì nên để trong ngoặc đơn để xác định rõ thứ tự ưu tiên 
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/NguyenDucThang/src/main/java/LeapYear.java#L10

**Comment by vuvanquy1998** [comment]
Alo , ô sửa xong báo t, để t xem và đóng issues nhé

**Comment by nguyenthang98** [comment]
T sửa rồi nhé. Review lại hộ tôi với.
