### ISSUE TITLE
NguyenThiQuynh

### ISSUE THREAD

**Issue by vuvanquy1998** [truonganhhoang/int3117-2018#120]
- Bạn Quỳnh ơi, nên kiểm tra cả trường hợp đúng và sai chứ nhỉ  :) ;) , các trường hợp biên đặc biệt như số lớn nhất ở đầu, ở cuối... 
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/NguyenThiQuynh/JUnitTest.java#L12
- Dòng trống nên được đặt ở giữa biến cục bộ cuối và câu lệnh đầu tiên trong một hàm
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/NguyenThiQuynh/JUnitTest.java#L15
- Nhận xét nửa Anh nửa Việt nè :)))
 https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/NguyenThiQuynh/JUnitTest.java#L6

**Comment by vuvanquy1998** [comment]
Quỳnh ơi, sửa xong chưa để, t đóng issues

**Comment by layer-quynh** [comment]
T sửa rồi, xem lại xem đúng chưa
