### ISSUE TITLE
NguyenTrungDuc

### ISSUE THREAD

**Issue by NgoQuangManh** [truonganhhoang/int3117-2018#153]
https://github.com/truonganhhoang/int3117-2018/blob/af756f1fc096948fb51dd3e06a7e7169be5423a7/NguyenTrungDuc/Shop/Source/Main.java#L7

Xóa các dòng code bị lỗi.

**Comment by caoboiyb** [comment]
Mình đã xoá nhé, bạn có thể closed được rồi
