### ISSUE TITLE
DamDinhDinh

### ISSUE THREAD

**Issue by shin0286** [truonganhhoang/int3117-2018#159]
https://github.com/truonganhhoang/int3117-2018/blob/af756f1fc096948fb51dd3e06a7e7169be5423a7/DamDinhDinh/SumPositiveNumberOfArrayTest.java#L24
- giữa các hàm nên có khoảng cách thống nhất (1 dòng cách)
- nên có thêm 1 số test case đặc biệt như mảng toàn phần tử âm hoặc mảng rỗng

**Comment by DamDinhDinh** [comment]
Xin lỗi giờ mình mới hoàn thành.
Mình thêm test case mảng toàn phần tử âm rồi, phần mảng rỗng do quên nên phải tạo pull request lần 2 chưa được.
Bạn close giúp mình với.
Many thanks
