### ISSUE TITLE
VuThiThuyThuy

### ISSUE THREAD

**Issue by shin0286** [truonganhhoang/int3117-2018#160]
https://github.com/truonganhhoang/int3117-2018/blob/af756f1fc096948fb51dd3e06a7e7169be5423a7/VuThiThuyThuy/bcnnTest.java#L6
- Đã dùng annotation thì vì sao còn phải viết thêm hàm main test
- Cần viết thêm các test case đặc biệt (a là bội của b, a hoặc b bằng 0 hoặc MAX_INT, v.v)

**Comment by shin0286** [comment]
cần chú tab đầu dòng

**Comment by shin0286** [comment]
mới có 1 test case, nên viết thêm tc cho TH đặc biệt như trên

**Comment by VuThuyThuy97** [comment]
trường hợp a là bội của b, max_int đã xử lý được sẵn trong code cũ. trường hợp a hoặc b bằng 0 đã update, chờ merge pull request
