### ISSUE TITLE
TranTuanAnh

### ISSUE THREAD

**Issue by MyoDaisy** [truonganhhoang/int3117-2018#171]
https://github.com/truonganhhoang/int3117-2018/blob/af756f1fc096948fb51dd3e06a7e7169be5423a7/TranTuanAnh/MyMath.java#L2
Mã nguồn tốt, đúng chuẩn.

**Comment by tuananh97** [comment]
c closed issue này đi nhé

**Comment by MyoDaisy** [comment]
ok c
