### ISSUE TITLE
Nguyễn Thị Xoan

### ISSUE THREAD

**Issue by trongmanh19** [truonganhhoang/int3117-2018#188]
trong hàm kiểm tra số nguyên tố, k cần phải else nữa mà có thể return luôn vì nếu code đoạn trên được thực hiện thì khi gặp return hàm đã kết thúc:
`   if (n > 1) {
         for(int i = 2; i <= Math.sqrt(n); i++){ 
             if(n % i == 0) 
                return false;
            }
        return true;
    }
    else 
        return false;
 `
Nên đặt tên biến có ý nghĩa

**Comment by XoanNguyen** [comment]
- Đặt tên biến trong trường hợp này vẫn chấp nhận được
- Hàm kiểm tra số nguyên tố để else không ảnh hưởng đến kết quả chạy của hàm
