### ISSUE TITLE
Cập nhật thông tin vào danh sách lớp học

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/int3117-2018#2]
Cập nhật thông tin cá nhân vào các cột bôi màu vàng sau:

https://docs.google.com/spreadsheets/d/1DoR8nWm3PGEO9d54U1od9wTBtDthCuYSAmD5Bqvvhkw/edit#gid=1574496422&range=G3:J3

Hạn 29/8/2018.

**Comment by hieutm2198** [comment]
Thưa thầy, em là sinh viên mới đăng ký vào lớp mình ngày 30/08  nên em đã bỏ lỡ mất buổi học đầu tiên (27/08) và trong danh sách lớp học chưa có tên của em. Thầy có thể cho phép em được bổ sung thông tin được không ạ?
Email của em là tranminhhieu2198@gmail.com.
Em cảm ơn thầy.

**Comment by truonganhhoang** [comment]
Em comment vào dòng trống thông tin để mình bổ sung và hỏi các bạn về bài
tập phải làm nhé.
