### ISSUE TITLE
Nhóm 3

### ISSUE THREAD

**Issue by daolq98** [truonganhhoang/int3117-2018#249]
Report bug sachmem.vn
Khi chọn đáp án rồi bấm chốt, trong thời gian kiểm tra kết quả chuyển sang câu hỏi khác thì câu vừa chọn đáp án không được tính mà tính cho câu mới chuyển sang
ví dụ: chọn câu 5 đáp án A, trong lúc kiểm tra đáp án chuyển sang câu 9 thì đáp án câu 5 đúng hay sai sẽ tính vào câu 9 và câu 5 đánh dấu chưa làm và không được chọn lại nữa. Tổng số câu đã làm sẽ không được tính câu 5

**Comment by minhth1905** [comment]
đã fix
