### ISSUE TITLE
Nhóm 21, Bug sach mem

### ISSUE THREAD

**Issue by Bitagi97** [truonganhhoang/int3117-2018#250]
![44530631_352169222222679_2705201691304656896_n](https://user-images.githubusercontent.com/18100634/47286378-ab855000-d618-11e8-9273-3d24e6e6bad5.png)
![44498964_2120963364834400_7006792191947309056_n 1](https://user-images.githubusercontent.com/18100634/47286379-ac1de680-d618-11e8-9969-24639f99c079.png)

**Comment by minhth1905** [comment]
đã fix
