### ISSUE TITLE
Nhóm 11 - Bug sách mềm

### ISSUE THREAD

**Issue by NgoHaiYen** [truonganhhoang/int3117-2018#252]
![image](https://user-images.githubusercontent.com/25661344/47304553-2b2f1100-d651-11e8-8c4a-22e3767dcf1e.png)

**Comment by minhth1905** [comment]
Câu hỏi này bị lỗi gì bạn, bạn cho mình link câu hỏi này được ko?

**Comment by NgoHaiYen** [comment]
Đáp án đúng là 3 câu đó.
Bạn mình khoanh ba đáp án đó và đúng.

**Comment by minhth1905** [comment]
đã fix
