### ISSUE TITLE
Nhóm 14 - bug sách mềm

### ISSUE THREAD

**Issue by daoduongvt97** [truonganhhoang/int3117-2018#253]
sau khi hoàn tất bài thi nhưng nếu vào lại vẫn có thể làm tiếp những câu nối với nhau, ví dụ câu 80 khi đang làm làm chưa xong, hết thời gian nhưng vào lần 2 sắp xếp lại đúng vẫn được tính điểm cho câu đó

**Comment by truonganhhoang** [comment]
sau khi làm bài người học được luyện tiếp nhưng chỉ tính kết quả lần đầu..
