### ISSUE TITLE
Nhóm 19 - bug sách mềm

### ISSUE THREAD

**Issue by tuananh97** [truonganhhoang/int3117-2018#255]
Đáp án 2 câu này sai, bị ngược đáp án do 2 câu trái nghĩa nhau
![a](https://user-images.githubusercontent.com/17721857/47617779-7b98e980-dafd-11e8-98e4-814d9b5caec2.png)
![bb](https://user-images.githubusercontent.com/17721857/47617784-83588e00-dafd-11e8-807f-0a9c5b4b2b92.png)

**Comment by truonganhhoang** [comment]
fixed
