### ISSUE TITLE
Thư mục cá nhân

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/int3117-2018#26]
- Các thư mục cá nhân các em để ở gốc của repo, chứ không để trong thư mục của nhóm.
- Tên các nhóm để theo mẫu chung: NhomX trong đó X là số của nhóm.
- Trong thư mục cá nhân các em chỉ để mã nguồn và các files dự án cần thiết, không đưa các file trung gian, có thể dịch tạo lại lên repo. 
- Các em kiểm tra lại repo chính này và cập nhật lại để lần tới nộp bài sửa các vấn đề trên nếu còn.

**Comment by Lego1st** [comment]
Thầy ơi, tên nhóm NhomX thì ghi ở chỗ nào ạ ?

**Comment by Neokun** [comment]
giờ muốn sửa lại các vấn đề trên thì pull request lại ạ ?

**Comment by truonganhhoang** [comment]
ừ, sửa thì các em đồng bộ repo này trước, rồi pull request lại để sửa, chứ ko sửa trực tiếp trên repo đang có. 

Trước khi sửa, nói chung nên pull bản mới nhất về.
