### ISSUE TITLE
Nhóm 21- Bug sách mềm , bug coi lại bài làm

### ISSUE THREAD

**Issue by Bitagi97** [truonganhhoang/int3117-2018#317]
Vào xem lại bài làm thì thấy : 

![image](https://user-images.githubusercontent.com/18100634/49009382-0cb5bb80-f1a3-11e8-8f74-d705e2eda7fa.png)

nhưng bên ngoài màn hình : 

![image](https://user-images.githubusercontent.com/18100634/49009491-4b4b7600-f1a3-11e8-89cf-57a0bc170c4f.png)

**Comment by minhth1905** [comment]
đã fix
