### ISSUE TITLE
Bài tập tuần 14 tìm hiểu công cụ phân tích tĩnh (static analysis)

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/int3117-2018#319]
Mỗi nhóm cài đặt và dùng thử một công cụ phân tích tĩnh và làm video demo khoảng 5 phút, không quá 10 phút, sau đó viết gdoc giới thiệu hướng dẫn sử dụng tool đó để các bạn khác làm theo được.

**Comment by Lego1st** [comment]
Nhóm 4: Nguyễn Minh Châu, Phí Hoàng Linh, Đinh Hà Nam, Nguyễn Trung Nghĩa [Pylint](https://www.youtube.com/watch?v=xnhDSeDXgAQ&feature=youtu.be)
