### ISSUE TITLE
Bài tập trên hoclieu.sachmem.vn không được tính điểm

### ISSUE THREAD

**Issue by Lego1st** [truonganhhoang/int3117-2018#320]
Thầy ơi, "Bài 6:  ISTQB Test Management" e có làm trên lớp, buổi học 12/11 nhưng có vẻ như kết quả của các bạn làm tại lớp hôm đấy đều bị reset và không được tính đúng không ạ ? @truonganhhoang

**Comment by guiltylotus** [comment]
Thưa thầy, không chỉ bài 6 mà những 3 4 5 7 của em cũng gặp trường hợp tương tự bạn Nghĩa ạ.

**Comment by truonganhhoang** [comment]
Các bài đầu chủ yếu để các em học, luyện, nên phần mềm có chỉnh sửa, nên ko tính điểm nhé.

Bài cuối, 8, mình sẽ lấy điểm chuyên cần.
