### ISSUE TITLE
ISTQB trên hoclieu.sachmem

### ISSUE THREAD

**Issue by phucnv282** [truonganhhoang/int3117-2018#321]
Em thưa thầy, em là sinh viên Nguyễn Văn Phúc, bài tập về ISTQB trên trang hoclieu.sachmem e đã làm, làm xong có thấy điểm nhưng từ tuần trước thì không còn được ghi nhận điểm trên trang hoclieu.sachmem nữa, thầy có thể xem lại giúp em với ạ.

**Comment by nguyenthang98** [comment]
Em cũng bị trường hợp giống bạn Phúc ạ. Mong thầy có thể xem lại giúp cho em.
Sinh viên Nguyễn Đức Thắng.

**Comment by piggy2303** [comment]
Thưa thầy em là Nguyễn Tuấn Anh, em đã tất cả làm bài tập ISTQB trên web từ hôm 1/11 nhưng hôm nay khi vào lại thì toàn bộ điểm đã bị mất ạ,
Mong thầy có thể xem lại giúp em
Nguyễn Tuấn Anh - k60clc - 15021849

**Comment by truonganhhoang** [comment]
mấy bài đầu sẽ ko tính điểm, chủ yếu để các em học, luyện.. mình tính điểm bài cuối cùng số 8 thôi nhé.
