### ISSUE TITLE
Thắc mắc điểm giữa kì 

### ISSUE THREAD

**Issue by taikhoan1cualoc** [truonganhhoang/int3117-2018#323]
em thưa thầy em là Trần Đức Lộc MSSV 15020922 có thắc mắc điểm điểm danh của em cột w8 em có điểm danh nhưng ở cột n8 lại k có điểm, và em có 2 điểm phát biểu nhưng không được ghi. Mong thầy xem xét em cảm ơn thầy.

**Comment by truonganhhoang** [comment]
Cột w8 mình ko lấy các điểm danh thêm vào sau, chỉ những điểm danh trong
giờ học đó mới tính.

Điểm phát biểu các em tự giác điền vào và các bạn kiểm tra lẫn nhau. Mình
ko tự điền điểm phát biểu của các em.

TAH

**Comment by taikhoan1cualoc** [comment]
Vâng em cảm ơn thầy do em nhờ các bạn nhóm điểm danh sửa hộ nên chắc các
bạn sửa lúc sau ạ em mong thầy xem xét cho em ạ em cảm ơn

Vào Th 3, 18 thg 12, 2018 lúc 20:18 Hoàng Trương <notifications@github.com>
đã viết:

**Comment by truonganhhoang** [comment]
điểm danh sau giờ học ko đc tính, lúc đó bạn đọc tên em phải có để bạn tick
vào chứ.

TAH
