### ISSUE TITLE
ĐƠN XIN XEM XÉT LẠI ĐIỂM TÌM HIỂU CÔNG CỤ PHÂN TÍCH TĨNH NHÓM 9

### ISSUE THREAD

**Issue by toantran24** [truonganhhoang/int3117-2018#324]
Em thưa thầy,
Tên em là Trần Quang Toàn, học sinh lớp K61-CC
Nhóm em là nhóm 9 gồm có 4 bạn:
Trần Quang Toàn
Nguyễn Đức Thắng
Nguyễn Văn Phúc
Nguyễn Thị Nhàn
Về bài tập nộp tư liệu công cụ phân tích tĩnh, nhóm em có làm đầy đủ cả video và tài liệu nhưng lúc em lên xem điểm thấy chấm mất tài liệu. Có thể bạn nào đó đã lỡ tay xóa mất tài liệu của bọn em. Em mong thầy xem lại giúp bọn em với ạ.
Dưới đây là ảnh tài liệu em làm và được mở lần cuối vào ngày 3/12

![rips](https://user-images.githubusercontent.com/42737186/50153712-cf53d200-02f9-11e9-9d7b-a355a95402ae.PNG)

Và đây là link tài liệu của bọn em ạ (vẫn còn ghi chỉnh sửa lần cuối vào ngày 2/12)

https://docs.google.com/document/d/1Xf_YyMSlKosnHZlNnpSHRlxshSY2XSoWxGEpnfLgHlk/edit#heading=h.4jy7pkxkkp0y

Em cảm ơn thầy

**Comment by truonganhhoang** [comment]
Mình đã điều chỉnh rồi nhé.

TAH
