### ISSUE TITLE
NguyenDucThang

### ISSUE THREAD

**Issue by layer-quynh** [truonganhhoang/int3117-2018#65]
- Nên xóa những dòng comment trống thừa.
- Comment thêm cho hàm.
- Format lại khoảng trắng ở 1 số chỗ như: ở câu lệnh if thứ 2, trước và sau dấu ' : ' ở hàm main.

**Comment by nguyenthang98** [comment]
Quỳnh ơi review lại hộ tớ với.

**Comment by layer-quynh** [comment]
Ok nhé
