### ISSUE TITLE
NgoHaiYen

### ISSUE THREAD

**Issue by devtuananh** [truonganhhoang/int3117-2018#66]
https://github.com/truonganhhoang/int3117-2018/blob/617b507bcee8b640564e854ef5f7e869211338e6/NgoHaiYen/test/FibonacciTest.java#L3
C nên xóa bỏ dòng trống chỗ này

**Comment by NgoHaiYen** [comment]
t nghĩ đây là mình import thường và import static thì nên để tách ra cho dễ phân biệt
