### ISSUE TITLE
VuVanQuy

### ISSUE THREAD

**Issue by quannguyen0510** [truonganhhoang/int3117-2018#78]
Mã nguồn ổn, tuy nhiên cách trình bày chưa tốt, có nhiều khoảng trống thừa, nên chia ra thành nhiều test case với nhiều trường hợp.

**Comment by vuvanquy1998** [comment]
Em sửa xong rồi đấy đại ca, bao giờ thầy đồng ý merge vào thì đại ca xem lại hộ em nhé !!!

**Comment by vuvanquy1998** [comment]
Xong rồi thì đóng issues lại đi đại ca Quân ơi
