### ISSUE TITLE
TruongNgocDuc

### ISSUE THREAD

**Issue by toantruongcs** [truonganhhoang/int3117-2018#83]
https://github.com/truonganhhoang/int3117-2018/blob/85b31bd56f4fcfbe800245d9fc0542c5f7ac23f6/TruongNgocDuc/Test.java#L6
Mã nguồn tốt, đúng chuẩn, cần thêm nhiều test-case hơn

**Comment by MyoDaisy** [comment]
bạn đóng issue giúp mình nhé
